name: 'Sphinx Build'
description: 'Builds documentation using Sphinx'
author: 'Ammar Askar'
branding:
  icon: 'book'
  color: 'yellow'
inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make latexpdf
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apt-get update -y && apt-get install -y perl"
    required: false
  pip-requirements:
    description:
      The path to the pip requirements file, relative to the root of the
      project.
    required: false
  conda-environment:
    description:
      The path to the Conda environment file, relative to the root of the
      project.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
